### ISSUE TITLE
Multiple search phone number search available?

### ISSUE THREAD

**Issue by fiuderazes** [ritiek/trunofficial#2]
Is it possible to make a single query with multiple phone numbers as arguments ? If yes..how can I make it.. Thank you

**Comment by ritiek** [comment]
No, this is not possible yet. At the moment, you can pass only one phone number at a time.

**Comment by ritiek** [comment]
Closed by #6.

It should be worth noting that this new feature of searching multiple phone numbers at once involves looping through the phone numbers and all the phone numbers are not accessed from the Truecaller database in a single request. I was unable to get info for multiple phone numbers in a single request.
