### ISSUE TITLE
Every Number has a prefix "+91"

### ISSUE THREAD

**Issue by navanchauhan** [ritiek/trunofficial#3]
Is it possible to change the prefix to the desired input

**Comment by ritiek** [comment]
This is probably happening due to the request parameters being used in [here](https://github.com/ritiek/trunofficial/blob/1d541101abd6918b703a655efb4a26084d4811cd/trunofficial/trunofficial.py#L16-L27). I'll do some more testing to see if this can be fixed but I can't say for sure.

**Comment by flamechair** [comment]
Hi, I've done some research and was able to extract the following parameters:
```
q=<Number to search for>
&countryCode=US
&type=4
&locAddr=
&placement=SEARCHRESULTS,HISTORY,DETAILS
&adId=<Unique ID>
&clientId=1
&myNumber=<Another Unique ID>
&registerId=<Unique Number>
&encoding=json HTTP/1.1
```

This might be cause by missing the `countryCode` parameter, as the number I searched for was a US number.

**Comment by ritiek** [comment]
@iamtpage You're right. I removed the `countryCode` assuming Truecaller would automatically figure that out. I am still confused why it would default to some country (that too my home country haha) instead of returning a bad response. I'll make a fix for this soon!

**Comment by flamechair** [comment]
If you used your credentials in the source code, then Truecaller might have
a "default" country code setting that is your country code if none are
given, although I haven't tested that theory yet, but it would make sense.

**Comment by navanchauhan** [comment]
Can't we ask the user to supply the country code ?

**Comment by ritiek** [comment]
@navanchauhan Yep, I added this in release v0.2.3 with 23eb940f6cab25011fb7104e176b2738be3781fe.

`trunofficial.search(123456789)` will now set defaults to the country you are making requests from.
`trunofficial.search(123456789, cc="US")` will pass the country code for US.

`$ trunofficial 123456789 -c US` for command line usage.

I guess this can be closed now.
